# ASSIGNMENT-2 MULTIPLE LINEAR REGRESSION

In [3]:
import warnings
warnings.simplefilter("ignore")

In [4]:
pip install pandas

In [5]:
import numpy as np
import pandas as pd

In [6]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [7]:
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
my_data=pd.read_csv("Admission_Predict.csv")

In [9]:
my_data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

    Research  Chance of Admit   
0        Yes              0.92  
1        Yes              0.76  
2        Yes              0.72  
3        Yes              0.80  
4         No              0.65  
..       ...               ...  
395      Yes              0.82  
396      Yes              0.84  
397      Yes              0.91  
398       No              0.67  
399      Yes              0.95  

[400 rows x 9 columns]

In [40]:
my_data2=my_data.drop(["Serial No.",  "Research",],axis=1)

In [41]:
my_data2

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0          337          118                  4  4.5   4.5  9.65   
1          324          107                  4  4.0   4.5  8.87   
2          316          104                  3  3.0   3.5  8.00   
3          322          110                  3  3.5   2.5  8.67   
4          314          103                  2  2.0   3.0  8.21   
..         ...          ...                ...  ...   ...   ...   
395        324          110                  3  3.5   3.5  9.04   
396        325          107                  3  3.0   3.5  9.11   
397        330          116                  4  5.0   4.5  9.45   
398        312          103                  3  3.5   4.0  8.78   
399        333          117                  4  5.0   4.0  9.66   

     Chance of Admit   
0                0.92  
1                0.76  
2                0.72  
3                0.80  
4                0.65  
..                ...  
395              0.82  
396              0.84  
397              0.91  
398              0.67  
399              0.95  

[400 rows x 7 columns]

In [115]:
x=my_data2.iloc[:,:-2].values
y=my_data2.iloc[:,6].values

In [116]:
x

array([[337. , 118. ,   4. ,   4.5,   4.5],
       [324. , 107. ,   4. ,   4. ,   4.5],
       [316. , 104. ,   3. ,   3. ,   3.5],
       ...,
       [330. , 116. ,   4. ,   5. ,   4.5],
       [312. , 103. ,   3. ,   3.5,   4. ],
       [333. , 117. ,   4. ,   5. ,   4. ]])

In [117]:
y

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

# SPLITTING THE DATASET

In [118]:
pip install scikit.learn

Note: you may need to restart the kernel to use updated packages.


In [119]:
from sklearn.model_selection import train_test_split

In [120]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [121]:
x_train

array([[319. , 110. ,   3. ,   3. ,   2.5],
       [325. , 111. ,   3. ,   3. ,   3.5],
       [320. , 103. ,   3. ,   3. ,   3. ],
       ...,
       [290. , 104. ,   4. ,   2. ,   2.5],
       [339. , 119. ,   5. ,   4.5,   4. ],
       [322. , 110. ,   4. ,   4. ,   5. ]])

In [122]:
x_test

array([[309. , 105. ,   5. ,   3.5,   3.5],
       [308. , 110. ,   4. ,   3.5,   3. ],
       [326. , 110. ,   3. ,   3.5,   3.5],
       [306. , 105. ,   2. ,   3. ,   2.5],
       [316. , 105. ,   3. ,   3. ,   3.5],
       [309. , 100. ,   2. ,   3. ,   3. ],
       [312. , 109. ,   3. ,   3. ,   3. ],
       [312. , 104. ,   3. ,   3.5,   4. ],
       [332. , 118. ,   2. ,   4.5,   3.5],
       [331. , 117. ,   4. ,   4.5,   5. ],
       [300. , 105. ,   1. ,   1. ,   2. ],
       [333. , 113. ,   5. ,   4. ,   4. ],
       [320. , 110. ,   2. ,   4. ,   3.5],
       [302. ,  99. ,   1. ,   2. ,   2. ],
       [328. , 112. ,   4. ,   4. ,   4.5],
       [311. , 104. ,   2. ,   2. ,   2. ],
       [312. ,  98. ,   1. ,   3.5,   3. ],
       [329. , 110. ,   2. ,   4. ,   3. ],
       [315. ,  99. ,   2. ,   3.5,   3. ],
       [313. , 107. ,   3. ,   4. ,   4.5],
       [329. , 119. ,   4. ,   4.5,   4.5],
       [327. , 113. ,   4. ,   4.5,   5. ],
       [301. , 106. ,   4. ,   2

In [123]:
y_train

array([0.72, 0.52, 0.64, 0.87, 0.62, 0.82, 0.57, 0.79, 0.82, 0.81, 0.78,
       0.93, 0.64, 0.5 , 0.9 , 0.75, 0.82, 0.64, 0.75, 0.77, 0.74, 0.56,
       0.78, 0.52, 0.8 , 0.75, 0.96, 0.62, 0.79, 0.68, 0.48, 0.74, 0.76,
       0.7 , 0.86, 0.91, 0.9 , 0.78, 0.7 , 0.59, 0.34, 0.71, 0.91, 0.69,
       0.47, 0.92, 0.94, 0.71, 0.74, 0.64, 0.93, 0.77, 0.61, 0.6 , 0.84,
       0.64, 0.84, 0.77, 0.63, 0.65, 0.81, 0.84, 0.65, 0.59, 0.7 , 0.57,
       0.7 , 0.81, 0.88, 0.56, 0.8 , 0.94, 0.79, 0.62, 0.93, 0.76, 0.78,
       0.85, 0.7 , 0.71, 0.8 , 0.79, 0.9 , 0.56, 0.67, 0.94, 0.74, 0.86,
       0.76, 0.47, 0.64, 0.81, 0.73, 0.71, 0.73, 0.89, 0.93, 0.86, 0.75,
       0.84, 0.67, 0.84, 0.71, 0.73, 0.76, 0.79, 0.54, 0.71, 0.85, 0.54,
       0.56, 0.8 , 0.64, 0.44, 0.72, 0.85, 0.7 , 0.95, 0.34, 0.75, 0.8 ,
       0.85, 0.74, 0.58, 0.66, 0.8 , 0.59, 0.88, 0.69, 0.84, 0.57, 0.97,
       0.75, 0.91, 0.65, 0.92, 0.44, 0.69, 0.65, 0.76, 0.62, 0.58, 0.46,
       0.63, 0.94, 0.46, 0.77, 0.89, 0.96, 0.62, 0.

In [124]:
y_train.shape

(320,)

In [125]:
y_test

array([0.71, 0.7 , 0.79, 0.73, 0.72, 0.48, 0.77, 0.71, 0.9 , 0.94, 0.58,
       0.89, 0.72, 0.57, 0.78, 0.42, 0.64, 0.84, 0.63, 0.72, 0.9 , 0.83,
       0.57, 0.47, 0.85, 0.67, 0.44, 0.54, 0.92, 0.62, 0.68, 0.73, 0.73,
       0.61, 0.55, 0.74, 0.64, 0.89, 0.73, 0.95, 0.71, 0.72, 0.75, 0.76,
       0.86, 0.7 , 0.39, 0.79, 0.61, 0.64, 0.71, 0.8 , 0.61, 0.89, 0.68,
       0.79, 0.78, 0.52, 0.76, 0.88, 0.74, 0.49, 0.65, 0.59, 0.87, 0.89,
       0.81, 0.9 , 0.8 , 0.76, 0.68, 0.87, 0.68, 0.64, 0.91, 0.61, 0.69,
       0.62, 0.93, 0.43])

In [126]:
y_test.shape

(80,)

In [127]:
from sklearn.linear_model import LinearRegression

In [128]:
lm=LinearRegression()

In [129]:
lm.fit(x_train,y_train)

LinearRegression()

In [130]:
ypredict=lm.predict(x_test)

In [131]:
ypredict

array([0.70495406, 0.69291556, 0.78568707, 0.6061276 , 0.7072867 ,
       0.61266304, 0.69047488, 0.70123163, 0.84580681, 0.91939541,
       0.5355264 , 0.88723487, 0.74162195, 0.51781579, 0.85874756,
       0.60496869, 0.60353639, 0.76946379, 0.63949446, 0.74132672,
       0.90220947, 0.8782899 , 0.63308567, 0.48060521, 0.77983364,
       0.58969337, 0.48580374, 0.66387244, 0.93032265, 0.69042713,
       0.6487936 , 0.75485794, 0.73610957, 0.5224955 , 0.80669824,
       0.7818399 , 0.72816583, 0.838756  , 0.62862955, 0.89615978,
       0.74981328, 0.70783332, 0.77099694, 0.81241033, 0.8446517 ,
       0.76371325, 0.64793911, 0.74234633, 0.60776892, 0.60320463,
       0.65944411, 0.77371828, 0.61629201, 0.93076649, 0.68931393,
       0.72455886, 0.85726216, 0.77727561, 0.79505189, 0.81963889,
       0.75510933, 0.43717637, 0.64999109, 0.53986851, 0.85621329,
       0.75803769, 0.71501617, 0.8492394 , 0.77342843, 0.7222336 ,
       0.64797025, 0.81683865, 0.75765817, 0.64489129, 0.93355

In [132]:
comparison=pd.DataFrame(x_test,columns=["GRE Score", "TOEFL Score", "University Rating", "SOP", "LOR ",])

In [133]:
comparison

GRE Score  TOEFL Score  University Rating  SOP  LOR 
0       309.0        105.0                5.0  3.5   3.5
1       308.0        110.0                4.0  3.5   3.0
2       326.0        110.0                3.0  3.5   3.5
3       306.0        105.0                2.0  3.0   2.5
4       316.0        105.0                3.0  3.0   3.5
..        ...          ...                ...  ...   ...
75      311.0        104.0                3.0  3.5   2.0
76      306.0        103.0                2.0  2.5   3.0
77      313.0        106.0                2.0  2.5   2.0
78      334.0        116.0                4.0  4.0   3.5
79      297.0         96.0                2.0  2.5   1.5

[80 rows x 5 columns]

In [134]:
comparison["AVL_o/p"]=y_test

In [135]:
comparison

GRE Score  TOEFL Score  University Rating  SOP  LOR   AVL_o/p
0       309.0        105.0                5.0  3.5   3.5     0.71
1       308.0        110.0                4.0  3.5   3.0     0.70
2       326.0        110.0                3.0  3.5   3.5     0.79
3       306.0        105.0                2.0  3.0   2.5     0.73
4       316.0        105.0                3.0  3.0   3.5     0.72
..        ...          ...                ...  ...   ...      ...
75      311.0        104.0                3.0  3.5   2.0     0.61
76      306.0        103.0                2.0  2.5   3.0     0.69
77      313.0        106.0                2.0  2.5   2.0     0.62
78      334.0        116.0                4.0  4.0   3.5     0.93
79      297.0         96.0                2.0  2.5   1.5     0.43

[80 rows x 6 columns]

In [136]:
comparison["predicted_o/p"]=ypredict

In [137]:
comparison

GRE Score  TOEFL Score  University Rating  SOP  LOR   AVL_o/p  \
0       309.0        105.0                5.0  3.5   3.5     0.71   
1       308.0        110.0                4.0  3.5   3.0     0.70   
2       326.0        110.0                3.0  3.5   3.5     0.79   
3       306.0        105.0                2.0  3.0   2.5     0.73   
4       316.0        105.0                3.0  3.0   3.5     0.72   
..        ...          ...                ...  ...   ...      ...   
75      311.0        104.0                3.0  3.5   2.0     0.61   
76      306.0        103.0                2.0  2.5   3.0     0.69   
77      313.0        106.0                2.0  2.5   2.0     0.62   
78      334.0        116.0                4.0  4.0   3.5     0.93   
79      297.0         96.0                2.0  2.5   1.5     0.43   

    predicted_o/p  
0        0.704954  
1        0.692916  
2        0.785687  
3        0.606128  
4        0.707287  
..            ...  
75       0.625947  
76       0.611429  
77       0.627317  
78       0.874822  
79       0.476725  

[80 rows x 7 columns]